openapi: 3.1.0
info:
  title: Six Cities API
  description: API для сервиса аренды жилья "Шесть городов"
  version: 1.0.0

servers:
  - url: http://localhost:4000/api
    description: Development server

tags:
  - name: users
    description: Управление пользователями
  - name: offers
    description: Управление предложениями по аренде
  - name: comments
    description: Управление комментариями

paths:
  /users/register:
    post:
      tags: [users]
      summary: Регистрация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
      responses:
        '201':
          description: Пользователь создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Ошибка валидации
        '409':
          description: Пользователь уже существует

  /users/login:
    post:
      tags: [users]
      summary: Авторизация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
        '401':
          description: Неверные учетные данные

  /users/logout:
    post:
      tags: [users]
      summary: Выход из системы
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Успешный выход
        '401':
          description: Не авторизован

  /users/check:
    get:
      tags: [users]
      summary: Проверка авторизации
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Информация о пользователе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Не авторизован

  /users/{userId}/avatar:
    post:
      tags: [users]
      summary: Загрузка аватара
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
      responses:
        '201':
          description: Аватар загружен
          content:
            application/json:
              schema:
                type: object
                properties:
                  filepath:
                    type: string
        '400':
          description: Файл не предоставлен
        '404':
          description: Пользователь не найден

  /offers:
    get:
      tags: [offers]
      summary: Получить список предложений
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 60
      responses:
        '200':
          description: Список предложений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OfferListItem'

    post:
      tags: [offers]
      summary: Создать предложение
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOffer'
      responses:
        '201':
          description: Предложение создано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'
        '400':
          description: Ошибка валидации
        '401':
          description: Не авторизован

  /offers/{offerId}:
    get:
      tags: [offers]
      summary: Получить предложение по ID
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Информация о предложении
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'
        '404':
          description: Предложение не найдено

    patch:
      tags: [offers]
      summary: Обновить предложение
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOffer'
      responses:
        '200':
          description: Предложение обновлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'
        '400':
          description: Ошибка валидации
        '403':
          description: Нет прав на редактирование
        '404':
          description: Предложение не найдено

    delete:
      tags: [offers]
      summary: Удалить предложение
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Предложение удалено
        '403':
          description: Нет прав на удаление
        '404':
          description: Предложение не найдено

  /offers/premium/{city}:
    get:
      tags: [offers]
      summary: Премиальные предложения по городу
      parameters:
        - name: city
          in: path
          required: true
          schema:
            type: string
            enum: [Paris, Cologne, Brussels, Amsterdam, Hamburg, Dusseldorf]
      responses:
        '200':
          description: Список премиальных предложений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OfferListItem'

  /offers/favorites:
    get:
      tags: [offers]
      summary: Получить избранные предложения
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Список избранных предложений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OfferListItem'
        '401':
          description: Не авторизован

  /offers/{offerId}/favorite:
    post:
      tags: [offers]
      summary: Добавить в избранное
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Добавлено в избранное
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'
        '401':
          description: Не авторизован
        '404':
          description: Предложение не найдено

    delete:
      tags: [offers]
      summary: Удалить из избранного
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Удалено из избранного
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'
        '401':
          description: Не авторизован
        '404':
          description: Предложение не найдено

  /comments/{offerId}:
    get:
      tags: [comments]
      summary: Получить комментарии к предложению
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Список комментариев
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        '404':
          description: Предложение не найдено

    post:
      tags: [comments]
      summary: Добавить комментарий
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateComment'
      responses:
        '201':
          description: Комментарий создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '400':
          description: Ошибка валидации
        '401':
          description: Не авторизован
        '404':
          description: Предложение не найдено

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        avatarUrl:
          type: string
        type:
          type: string
          enum: [обычный, pro]
      required: [id, name, email, type]

    CreateUser:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 15
        email:
          type: string
          format: email
        avatarUrl:
          type: string
          pattern: '.*\.(jpg|png)$'
        password:
          type: string
          minLength: 6
          maxLength: 12
        type:
          type: string
          enum: [обычный, pro]
      required: [name, email, password, type]

    LoginUser:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 6
          maxLength: 12
      required: [email, password]

    AuthToken:
      type: object
      properties:
        email:
          type: string
        token:
          type: string
      required: [email, token]

    Offer:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        city:
          $ref: '#/components/schemas/City'
        previewImage:
          type: string
        images:
          type: array
          items:
            type: string
          minItems: 6
          maxItems: 6
        isPremium:
          type: boolean
        isFavorite:
          type: boolean
        rating:
          type: number
          minimum: 1
          maximum: 5
        type:
          type: string
          enum: [apartment, house, room, hotel]
        bedrooms:
          type: integer
          minimum: 1
          maximum: 8
        maxAdults:
          type: integer
          minimum: 1
          maximum: 10
        price:
          type: integer
          minimum: 100
          maximum: 100000
        goods:
          type: array
          items:
            type: string
          minItems: 1
        author:
          $ref: '#/components/schemas/User'
        commentsCount:
          type: integer
        location:
          $ref: '#/components/schemas/Location'

    OfferListItem:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        type:
          type: string
          enum: [apartment, house, room, hotel]
        price:
          type: integer
        city:
          $ref: '#/components/schemas/City'
        previewImage:
          type: string
        isFavorite:
          type: boolean
        isPremium:
          type: boolean
        rating:
          type: number
        commentsCount:
          type: integer

    CreateOffer:
      type: object
      properties:
        title:
          type: string
          minLength: 10
          maxLength: 100
        description:
          type: string
          minLength: 20
          maxLength: 1024
        city:
          $ref: '#/components/schemas/CityDto'
        previewImage:
          type: string
        images:
          type: array
          items:
            type: string
          minItems: 6
          maxItems: 6
        isPremium:
          type: boolean
        type:
          type: string
          enum: [apartment, house, room, hotel]
        bedrooms:
          type: integer
          minimum: 1
          maximum: 8
        maxAdults:
          type: integer
          minimum: 1
          maximum: 10
        price:
          type: integer
          minimum: 100
          maximum: 100000
        goods:
          type: array
          items:
            type: string
            enum: [Breakfast, Air conditioning, Laptop friendly workspace, Baby seat, Washer, Towels, Fridge]
          minItems: 1
        location:
          $ref: '#/components/schemas/Location'
      required:
        - title
        - description
        - city
        - previewImage
        - images
        - isPremium
        - type
        - bedrooms
        - maxAdults
        - price
        - goods
        - location

    UpdateOffer:
      type: object
      properties:
        title:
          type: string
          minLength: 10
          maxLength: 100
        description:
          type: string
          minLength: 20
          maxLength: 1024
        city:
          $ref: '#/components/schemas/CityDto'
        previewImage:
          type: string
        images:
          type: array
          items:
            type: string
          minItems: 6
          maxItems: 6
        isPremium:
          type: boolean
        type:
          type: string
          enum: [apartment, house, room, hotel]
        bedrooms:
          type: integer
          minimum: 1
          maximum: 8
        maxAdults:
          type: integer
          minimum: 1
          maximum: 10
        price:
          type: integer
          minimum: 100
          maximum: 100000
        goods:
          type: array
          items:
            type: string
            enum: [Breakfast, Air conditioning, Laptop friendly workspace, Baby seat, Washer, Towels, Fridge]
          minItems: 1
        location:
          $ref: '#/components/schemas/Location'

    Comment:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        rating:
          type: integer
        author:
          $ref: '#/components/schemas/User'
        postDate:
          type: string
          format: date-time
      required: [id, text, rating, author, postDate]

    CreateComment:
      type: object
      properties:
        text:
          type: string
          minLength: 5
          maxLength: 1024
        rating:
          type: integer
          minimum: 1
          maximum: 5
      required: [text, rating]

    City:
      type: object
      properties:
        name:
          type: string
          enum: [Paris, Cologne, Brussels, Amsterdam, Hamburg, Dusseldorf]
        latitude:
          type: number
        longitude:
          type: number
      required: [name, latitude, longitude]

    CityDto:
      type: object
      properties:
        name:
          type: string
          enum: [Paris, Cologne, Brussels, Amsterdam, Hamburg, Dusseldorf]
        latitude:
          type: number
          minimum: -90
          maximum: 90
        longitude:
          type: number
          minimum: -180
          maximum: 180
      required: [name, latitude, longitude]

    Location:
      type: object
      properties:
        latitude:
          type: number
          minimum: -90
          maximum: 90
        longitude:
          type: number
          minimum: -180
          maximum: 180
      required: [latitude, longitude]

security:
  - bearerAuth: []
