openapi: 3.1.0
info:
  title: Six Cities API
  description: API для сервиса аренды жилья "Шесть городов"
  version: 1.0.0

servers:
  - url: http://localhost:4000/api
    description: Development server

tags:
  - name: users
    description: Управление пользователями
  - name: offers
    description: Управление предложениями по аренде
  - name: comments
    description: Управление комментариями

paths:
  /users/register:
    post:
      tags: [users]
      summary: Регистрация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
      responses:
        '201':
          description: Пользователь создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Ошибка валидации
        '409':
          description: Пользователь уже существует

  /users/login:
    post:
      tags: [users]
      summary: Авторизация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
        '401':
          description: Неверные учетные данные

  /users/logout:
    post:
      tags: [users]
      summary: Выход из системы
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Успешный выход
        '401':
          description: Не авторизован

  /users/check:
    get:
      tags: [users]
      summary: Проверка авторизации
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Информация о пользователе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Не авторизован

  /offers:
    get:
      tags: [offers]
      summary: Получить список предложений
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 60
      responses:
        '200':
          description: Список предложений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OfferShort'

    post:
      tags: [offers]
      summary: Создать предложение
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOffer'
      responses:
        '201':
          description: Предложение создано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'

  /offers/{offerId}:
    get:
      tags: [offers]
      summary: Получить предложение по ID
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Информация о предложении
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'
        '404':
          description: Предложение не найдено

    patch:
      tags: [offers]
      summary: Обновить предложение
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOffer'
      responses:
        '200':
          description: Предложение обновлено
        '403':
          description: Нет прав на редактирование
        '404':
          description: Предложение не найдено

    delete:
      tags: [offers]
      summary: Удалить предложение
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Предложение удалено
        '403':
          description: Нет прав на удаление
        '404':
          description: Предложение не найдено

  /offers/premium/{city}:
    get:
      tags: [offers]
      summary: Премиальные предложения по городу
      parameters:
        - name: city
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Список премиальных предложений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OfferShort'

  /offers/favorites:
    get:
      tags: [offers]
      summary: Получить избранные предложения
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Список избранных предложений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OfferShort'

  /offers/{offerId}/favorite:
    post:
      tags: [offers]
      summary: Добавить в избранное
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Добавлено в избранное
        '404':
          description: Предложение не найдено

    delete:
      tags: [offers]
      summary: Удалить из избранного
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Удалено из избранного
        '404':
          description: Предложение не найдено

  /comments/{offerId}:
    get:
      tags: [comments]
      summary: Получить комментарии к предложению
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Список комментариев
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'

    post:
      tags: [comments]
      summary: Добавить комментарий
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateComment'
      responses:
        '201':
          description: Комментарий создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '404':
          description: Предложение не найдено

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        avatarUrl:
          type: string
        type:
          type: string
          enum: [regular, pro]

    CreateUser:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        type:
          type: string
          enum: [regular, pro]
      required: [name, email, password, type]

    LoginUser:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required: [email, password]

    AuthToken:
      type: object
      properties:
        token:
          type: string

    Offer:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        city:
          type: string
        previewImage:
          type: string
        images:
          type: array
          items:
            type: string
        isPremium:
          type: boolean
        isFavorite:
          type: boolean
        rating:
          type: number
        type:
          type: string
          enum: [apartment, house, room, hotel]
        bedrooms:
          type: integer
        maxAdults:
          type: integer
        price:
          type: integer
        goods:
          type: array
          items:
            type: string
        host:
          $ref: '#/components/schemas/User'
        commentsCount:
          type: integer
        location:
          $ref: '#/components/schemas/Location'

    OfferShort:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        type:
          type: string
        price:
          type: integer
        city:
          type: string
        previewImage:
          type: string
        isFavorite:
          type: boolean
        isPremium:
          type: boolean
        rating:
          type: number
        commentsCount:
          type: integer

    CreateOffer:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        city:
          type: string
        previewImage:
          type: string
        images:
          type: array
          items:
            type: string
        isPremium:
          type: boolean
        type:
          type: string
        bedrooms:
          type: integer
        maxAdults:
          type: integer
        price:
          type: integer
        goods:
          type: array
          items:
            type: string
        location:
          $ref: '#/components/schemas/Location'

    UpdateOffer:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        isPremium:
          type: boolean
        type:
          type: string
        bedrooms:
          type: integer
        maxAdults:
          type: integer
        price:
          type: integer
        goods:
          type: array
          items:
            type: string

    Comment:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        rating:
          type: integer
        author:
          $ref: '#/components/schemas/User'
        postDate:
          type: string

    CreateComment:
      type: object
      properties:
        text:
          type: string
        rating:
          type: integer
      required: [text, rating]

    Location:
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number

security:
  - bearerAuth: []
